version: '3'
services:
  web_green:
    build: ./app
    image: dewansh26/ip-addr:v2 
    container_name: web_green
    expose:
      - "80"

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web_green
