version: '3'
services:
  web_blue:
    build: ./app
    image: dewansh26/ip-addr:v1
    container_name: web_blue
    expose:
      - "80"

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web_blue
